<?php
$this->headScript()->appendFile('/js/progressBar.js');
?>

<div class="progress">
    <div id="myBar" class="progress-bar progress-bar-striped" role="progressbar" aria-valuenow="6" aria-valuemin="0" aria-valuemax="100" style="width: 6%;">
        6%
    </div>
</div>

<button class="btn btn-success" onclick="move()">start</button>
<button id="reset" class="btn btn-danger" disabled>reset</button>


<div id="timestamp"></div>
